"""add tenant lead management and imports

Revision ID: 363baa1027b8
Revises: dd001d335ac3
Create Date: 2026-10-04 12:22:53.477803
"""
from collections.abc import Sequence
import uuid

from alembic import op
import sqlalchemy as sa


revision: str = '363baa1027b8'
down_revision: str | Sequence[str] | None = 'dd001d335ac3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ROLE_IDS = {
    "owner": uuid.UUID("10000000-0000-0000-0000-000000000001"),
    "operator": uuid.UUID("10000000-0000-0000-0000-000000000002"),
}
LEAD_PERMISSION_IDS = {
    "leads.import": uuid.UUID("40000000-0000-0000-0000-000000000001"),
    "leads.assign": uuid.UUID("40000000-0000-0000-0000-000000000002"),
    "leads.status": uuid.UUID("40000000-0000-0000-0000-000000000003"),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_lead_import_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='previewed', nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['t_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['t_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'created_by', 'snapshot_hash', name='uq_t_lead_import_preview_hash')
    )
    op.create_index('ix_t_lead_import_batch_tenant_created_by', 't_lead_import_batch', ['tenant_id', 'created_by'], unique=False)
    op.create_table('t_lead',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('tracking_id', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_original', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=160), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('email_status', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('facebook_url', sa.String(length=2048), nullable=True),
    sa.Column('instagram_url', sa.String(length=2048), nullable=True),
    sa.Column('x_url', sa.String(length=2048), nullable=True),
    sa.Column('github_url', sa.String(length=2048), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('company_website', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=160), nullable=True),
    sa.Column('company_size', sa.String(length=30), nullable=True),
    sa.Column('revenue_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('revenue_currency', sa.String(length=3), nullable=True),
    sa.Column('revenue_period', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='new', nullable=False),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('consent_status', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('consent_evidence', sa.Text(), nullable=True),
    sa.Column('consent_reference', sa.String(length=255), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint('(revenue_amount IS NULL AND revenue_currency IS NULL AND revenue_period IS NULL) OR (revenue_amount IS NOT NULL AND revenue_currency IS NOT NULL AND revenue_period IS NOT NULL)', name='ck_t_lead_revenue_complete'),
    sa.CheckConstraint('revenue_amount IS NULL OR revenue_amount >= 0', name='ck_t_lead_revenue_nonnegative'),
    sa.CheckConstraint('row_version >= 1', name='ck_t_lead_row_version_positive'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['t_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['t_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by'], ['t_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['t_lead_import_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['t_tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['t_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_id', name='uq_t_lead_tracking_id')
    )
    op.create_index('ix_t_lead_assigned_user_id', 't_lead', ['assigned_user_id'], unique=False)
    op.create_index('ix_t_lead_import_batch_id', 't_lead', ['import_batch_id'], unique=False)
    op.create_index('ix_t_lead_tenant_id', 't_lead', ['tenant_id'], unique=False)
    op.create_index('uq_t_lead_active_tenant_email', 't_lead', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('t_lead_customer_action',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('requires_verified_consent', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['t_lead.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['t_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_t_lead_customer_action_lead_status', 't_lead_customer_action', ['lead_id', 'status'], unique=False)
    op.create_table('t_lead_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['t_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['t_lead.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['t_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_t_lead_event_tenant_lead', 't_lead_event', ['tenant_id', 'lead_id'], unique=False)
    op.create_table('t_lead_import_row',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['t_lead_import_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['t_lead.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['t_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_t_lead_import_row_number')
    )
    op.create_index('ix_t_lead_import_row_batch_status', 't_lead_import_row', ['batch_id', 'status'], unique=False)
    permission_table = sa.table(
        't_permission',
        sa.column('id', sa.Uuid()),
        sa.column('key', sa.String()),
        sa.column('description', sa.String()),
    )
    role_permission_table = sa.table(
        't_role_permission',
        sa.column('role_id', sa.Uuid()),
        sa.column('permission_id', sa.Uuid()),
    )
    op.bulk_insert(
        permission_table,
        [
            {
                'id': permission_id,
                'key': key,
                'description': key.replace('.', ' ').title(),
            }
            for key, permission_id in LEAD_PERMISSION_IDS.items()
        ],
    )
    op.bulk_insert(
        role_permission_table,
        [
            {'role_id': role_id, 'permission_id': permission_id}
            for role_id in ROLE_IDS.values()
            for permission_id in LEAD_PERMISSION_IDS.values()
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_permission_table = sa.table(
        't_role_permission',
        sa.column('permission_id', sa.Uuid()),
    )
    permission_table = sa.table(
        't_permission',
        sa.column('id', sa.Uuid()),
    )
    op.execute(
        role_permission_table.delete().where(
            role_permission_table.c.permission_id.in_(LEAD_PERMISSION_IDS.values())
        )
    )
    op.execute(
        permission_table.delete().where(
            permission_table.c.id.in_(LEAD_PERMISSION_IDS.values())
        )
    )
    op.drop_index('ix_t_lead_import_row_batch_status', table_name='t_lead_import_row')
    op.drop_table('t_lead_import_row')
    op.drop_index('ix_t_lead_event_tenant_lead', table_name='t_lead_event')
    op.drop_table('t_lead_event')
    op.drop_index('ix_t_lead_customer_action_lead_status', table_name='t_lead_customer_action')
    op.drop_table('t_lead_customer_action')
    op.drop_index('uq_t_lead_active_tenant_email', table_name='t_lead', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_t_lead_tenant_id', table_name='t_lead')
    op.drop_index('ix_t_lead_import_batch_id', table_name='t_lead')
    op.drop_index('ix_t_lead_assigned_user_id', table_name='t_lead')
    op.drop_table('t_lead')
    op.drop_index('ix_t_lead_import_batch_tenant_created_by', table_name='t_lead_import_batch')
    op.drop_table('t_lead_import_batch')
    # ### end Alembic commands ###

