"""add login ids and tenant authorization

Revision ID: 4200410ff950
Revises: 92331236070f
Create Date: 2026-10-01 15:42:16.176815
"""
from collections.abc import Sequence
import uuid

from alembic import op
import sqlalchemy as sa


revision: str = '4200410ff950'
down_revision: str | Sequence[str] | None = '92331236070f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ROLE_IDS = {
    "owner": uuid.UUID("10000000-0000-0000-0000-000000000001"),
    "operator": uuid.UUID("10000000-0000-0000-0000-000000000002"),
    "staff": uuid.UUID("10000000-0000-0000-0000-000000000003"),
    "readonly": uuid.UUID("10000000-0000-0000-0000-000000000004"),
}
PERMISSION_KEYS = [
    "tenant.users.manage",
    "tenant.settings.manage",
    "templates.read",
    "templates.draft",
    "templates.approve",
    "workflows.read",
    "workflows.draft",
    "workflows.approve",
    "leads.read",
    "leads.manage",
    "leads.assigned.update",
    "audits.read",
    "audits.manage",
    "dashboard.read",
    "integrations.use",
]
PERMISSION_IDS = {
    key: uuid.UUID(f"20000000-0000-0000-0000-{index:012d}")
    for index, key in enumerate(PERMISSION_KEYS, start=1)
}
ROLE_PERMISSION_KEYS = {
    "owner": set(PERMISSION_KEYS),
    "operator": {
        "templates.read",
        "templates.draft",
        "workflows.read",
        "workflows.draft",
        "leads.read",
        "leads.manage",
        "audits.read",
        "audits.manage",
        "dashboard.read",
    },
    "staff": {
        "templates.read",
        "workflows.read",
        "leads.read",
        "leads.assigned.update",
        "dashboard.read",
    },
    "readonly": {
        "templates.read",
        "workflows.read",
        "leads.read",
        "audits.read",
        "dashboard.read",
    },
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_permission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('t_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('t_tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('t_role_permission',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['t_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    role_table = sa.table(
        "t_role",
        sa.column("id", sa.Uuid()),
        sa.column("key", sa.String()),
        sa.column("name", sa.String()),
    )
    permission_table = sa.table(
        "t_permission",
        sa.column("id", sa.Uuid()),
        sa.column("key", sa.String()),
        sa.column("description", sa.String()),
    )
    role_permission_table = sa.table(
        "t_role_permission",
        sa.column("role_id", sa.Uuid()),
        sa.column("permission_id", sa.Uuid()),
    )
    op.bulk_insert(
        role_table,
        [
            {"id": role_id, "key": key, "name": key.title()}
            for key, role_id in ROLE_IDS.items()
        ],
    )
    op.bulk_insert(
        permission_table,
        [
            {
                "id": permission_id,
                "key": key,
                "description": key.replace(".", " ").replace("_", " ").title(),
            }
            for key, permission_id in PERMISSION_IDS.items()
        ],
    )
    op.bulk_insert(
        role_permission_table,
        [
            {
                "role_id": ROLE_IDS[role_key],
                "permission_id": PERMISSION_IDS[permission_key],
            }
            for role_key, permission_keys in ROLE_PERMISSION_KEYS.items()
            for permission_key in sorted(permission_keys)
        ],
    )
    op.create_table('t_tenant_membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['t_role.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['t_tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_t_tenant_membership_tenant_user')
    )
    op.create_index('ix_t_tenant_membership_tenant_id', 't_tenant_membership', ['tenant_id'], unique=False)
    op.create_index('ix_t_tenant_membership_user_id', 't_tenant_membership', ['user_id'], unique=False)
    op.create_table('t_authorization_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('target_membership_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['t_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_membership_id'], ['t_tenant_membership.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['t_tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_membership_permission',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['t_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['membership_id'], ['t_tenant_membership.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['t_permission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'permission_id')
    )
    op.add_column(
        't_user',
        sa.Column('login_id', sa.String(length=50), nullable=True),
    )
    op.execute(
        "UPDATE t_user "
        "SET login_id = 'user-' || replace(CAST(id AS VARCHAR), '-', '')"
    )
    op.alter_column('t_user', 'login_id', nullable=False)
    op.create_check_constraint(
        'ck_t_user_login_id_format',
        't_user',
        "length(login_id) BETWEEN 5 AND 50 AND login_id NOT LIKE '%@%'",
    )
    op.create_index('uq_t_user_login_id_ci', 't_user', [sa.literal_column('lower(login_id)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_t_user_login_id_ci', table_name='t_user')
    op.drop_constraint('ck_t_user_login_id_format', 't_user', type_='check')
    op.drop_column('t_user', 'login_id')
    op.drop_table('t_membership_permission')
    op.drop_table('t_authorization_audit')
    op.drop_index('ix_t_tenant_membership_user_id', table_name='t_tenant_membership')
    op.drop_index('ix_t_tenant_membership_tenant_id', table_name='t_tenant_membership')
    op.drop_table('t_tenant_membership')
    op.drop_table('t_role_permission')
    op.drop_table('t_tenant')
    op.drop_table('t_role')
    op.drop_table('t_permission')
    # ### end Alembic commands ###

