"""add service requested to leads

Revision ID: e1c28a9ad51e
Revises: 363baa1027b8
Create Date: 2026-10-05 14:09:46.426465
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e1c28a9ad51e'
down_revision: str | Sequence[str] | None = '363baa1027b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_lead', sa.Column('service_requested', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_lead', 'service_requested')
    # ### end Alembic commands ###

